# Uncomment for Windows re-rendering only.
#
#matrix:
#  - [[VC_VERSION, 9], [CONDA_PY, 27]]
#  - [[VC_VERSION, 10], [CONDA_PY, 34]]
#  - [[VC_VERSION, 14], [CONDA_PY, 35]]

travis:
  secure:
    BINSTAR_TOKEN: GvyWsKD36Nv35v0qNpeNn0+0YYyDIvBTmEdxTuXCWjHFH3Ti977QXxs2hmVfM+Qch/tRokRANFSi5Gu7REjFH/5S/OPFdHX+Sk1P9zbsRN56ZrCkNaWg6quBDvSLboWCWB7xiGRPgIbxIuu6Z3Ob2Ej9+B2dKGt7vKu/ezvVv/BMdRygwM0IfFpvy182M10sVTx1/qvaWDBqmM/0Z/gIw+ZQ+S023Vhq2pGdwPG6sTPFTQoNSvtcUKy1MNTNCu+PS4iHRmtDN0zCGLdnZiaNUUEuwBmw3puqFemIhqcshrZpIXgFeGacqexCZy7D5L9BQZCpcuu4GqoEFamMXGyPn0vd712/Y1SEVbxg//zTHUJXDVW/DjNOJJg2eH0d0okd3qDZVMpYtqJ1bjADpfjTk1qOAB77S4g6dCtidj85RMRuEU1SzHfQYLNk9Rlww6uG7Ece2o3BKlk77njeeZUyTVw1aWnixw2PjAwpv2oCykSlfUh8YlVgQGnE3R0vi0C9DKo47PafxNiwf9FU7b9QNJQTbT3nDhjyZ/gGkxIpZhbqFTyX/z+j9DKfqnG+n8ujFUi5wNH1HiPmrDJaPGbYb1YxCFWjrLchk9QolVltuOEiG7j+CtfhuvIRFrZaIKt3dzpPdZ3eH5KxVfkNy/9L6LU9jeLfvnG6xa9cKGQEpDk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
