# Uncomment for Windows re-rendering only.
#
#matrix:
#  - [[VC_VERSION, 9], [CONDA_PY, 27]]
#  - [[VC_VERSION, 10], [CONDA_PY, 34]]
#  - [[VC_VERSION, 14], [CONDA_PY, 35]]

conda_forge_output_validation: true
